name: Gens
version: '${project.version}'
main: me.elmopog.gens.Gens
api-version: 1.17
authors: [ ElmoPog ]
description: An experimental gens plugin
commands:
  givegen:
    description: Command to get a gen
  reloadconfig:
    description: Command to reload the config.yml